export const TYPES = {
    POST_ONBOARDING_YOU_REQUEST: 'POST_ONBOARDING_YOU_REQUEST',
    POST_ONBOARDING_YOU_SUCCESS: 'POST_ONBOARDING_YOU_SUCCESS',
    POST_ONBOARDING_YOU_FAILED: 'POST_ONBOARDING_YOU_FAILED',
}