export const TYPES = {
    GET_AUTHENTICATION_REQUEST: 'GET_AUTHENTICATION_REQUEST',
    GET_AUTHENTICATION_SUCCESS: 'GET_AUTHENTICATION_SUCCESS',
    GET_AUTHENTICATION_FAILED: 'GET_AUTHENTICATION_FAILED',

    POST_SIGNUP_REQUEST: 'POST_SIGNUP_REQUEST',
    POST_SIGNUP_SUCCESS: 'POST_SIGNUP_SUCCESS',
    POST_SIGNUP_FAILED: 'POST_SIGNUP_FAILED',
}