export const TYPES = {
    GET_AUTHENTICATION_REQUEST: 'GET_AUTHENTICATION_REQUEST',
    GET_AUTHENTICATION_SUCCESS: 'GET_AUTHENTICATION_SUCCESS',
    GET_AUTHENTICATION_FAILED: 'GET_AUTHENTICATION_FAILED',
}